### ISSUE TITLE
在考虑是否可以调整一下两个wf的逻辑关系

### ISSUE THREAD

**Issue by barton0426** [KFERMercer/OpenWrt-CI#12]
感觉openwrt-ci.yml每日编译意义不大。是不是可以考虑merge-upstream.yml每天定时看看源是否有更新，然后如果更新了，触发openwrt-ci.yml启动一次编译

**Comment by KFERMercer** [comment]
> 感觉openwrt-ci.yml每日编译意义不大。

默认是推送触发编译.


> 是不是可以考虑merge-upstream.yml每天定时看看源是否有更新，然后如果更新了，触发openwrt-ci.yml启动一次编译

默认已经是了. 
merge-upstream会在每天三点半检查上游更新并推送 (没有则不推送), openwrt-ci会在推送后编译.

**Comment by barton0426** [comment]
somehow 我看到的是旧版本 最新的确实没问题 不过merge*.yml里 还是有个推送触发 不太理解为什么这么设置
