### ISSUE TITLE
开启UEFI后编译失败

### ISSUE THREAD

**Issue by kiddin9** [KFERMercer/OpenWrt-CI#13]
复制的本项目的openwrt-ci.yml文件,除了把
          # cat >> .config <<EOF
          # CONFIG_EFI_IMAGES=y
          # EOF
去掉了# 改成了
          cat >> .config <<EOF
          CONFIG_EFI_IMAGES=y
          EOF
其他没做任何修改

**Comment by KFERMercer** [comment]
经测试正常.
