### ISSUE TITLE
请问下大佬！脚本是否支持 使用SSH 云menuconfig

### ISSUE THREAD

**Issue by xunqiuhuiyi** [KFERMercer/OpenWrt-CI#15]
K老大 上周P3TERX通过 tmate 连接到 GitHub Ac­tions 虚拟服务器环境，可直接进行 make menuconfig 操作生成编译配置，不需要修改yml内容了，请问是CI是否也可以支持SSH 云menuconfig。

**Comment by KFERMercer** [comment]
谢邀, 不支持. 想不到有什么支持的必要.

**Comment by kiddin9** [comment]
> K老大 上周P3TERX通过 tmate 连接到 GitHub Ac­tions 虚拟服务器环境，可直接进行 make menuconfig 操作生成编译配置，不需要修改yml内容了，请问是CI是否也可以支持SSH 云menuconfig。

自己在配置文件中编译步骤前加一条
```
      - name: SSH
        uses: P3TERX/debugger-action@master
```
