### ISSUE TITLE
将自动更新固件文件上传后出错

### ISSUE THREAD

**Issue by engineerlzk** [KFERMercer/OpenWrt-CI#17]
首先感谢大大自动编译脚本，让我等小白也学会了如何编译固件。
当我按照您的教程将自动更新代码文件merge-upstream.yml下载并上传后，发现如下错误提示，请问如何解决？谢谢指教！
.github/workflows/merge-upstream.yml

Invalid Workflow File

DETAILS

You have an error in your yaml syntax on line 122
ANNOTATIONS

 Check failure on line 122 in .github/workflows/merge-upstream.yml

 @github-actions
github-actions
/ .github/workflows/merge-upstream.yml

Parse error
You have an error in your yaml syntax on line 122

**Comment by KFERMercer** [comment]
首先, merge-upstream.yml只有44行.
