### ISSUE TITLE
修改好同步的文件的分支字段，但是运行后没有同步最新源代码

### ISSUE THREAD

**Issue by bonnyandsky** [KFERMercer/OpenWrt-CI#18]
upstream已经编译成功了
![1](https://user-images.githubusercontent.com/30990861/70444026-30a91e00-1ad4-11ea-8c2f-b6efe8f9ba47.png)
然后我看了下分支ledenew下面的源代码还是和master一样的，并没有跟新coolsnowwolf的最新源码
![2](https://user-images.githubusercontent.com/30990861/70444028-30a91e00-1ad4-11ea-98d1-35e3aacd9927.png)
这个是从你这里复制过来的2个脚本文件
![3](https://user-images.githubusercontent.com/30990861/70444029-3141b480-1ad4-11ea-9690-7f442ef67441.png)
自动同步的文件已经把相关的master替换成ledenew了
![5](https://user-images.githubusercontent.com/30990861/70444030-3141b480-1ad4-11ea-8599-7711139fdfbd.png)
请问是哪里的问题？还是说cron：30  19 × × ×这里是表示要每天19点30分才会自动同步？

**Comment by bonnyandsky** [comment]
我尝试着把utc时间改了下，然而他还是没有同步到最新的源码

![无标题](https://user-images.githubusercontent.com/30990861/70447326-816f4580-1ad9-11ea-80e7-61227443d39d.png)

**Comment by KFERMercer** [comment]
> 请问是哪里的问题？还是说cron：30 19 × × ×这里是表示要每天19点30分才会自动同步？

utc时间. 换算成北京时间是凌晨三点半.

> 我尝试着把utc时间改了下，然而他还是没有同步到最新的源码

push函数的问题. 写脚本初期没有考虑到会有人放进非master分支. 有时间我会修复这个问题.

**Comment by bonnyandsky** [comment]
> > 请问是哪里的问题？还是说cron：30 19 × × ×这里是表示要每天19点30分才会自动同步？
> 
> utc时间. 换算成北京时间是凌晨三点半.
> 
> > 我尝试着把utc时间改了下，然而他还是没有同步到最新的源码
> 
> push函数的问题. 写脚本初期没有考虑到会有人放进非master分支. 有时间我会修复这个问题.

我这也是被逼的，为了确保有一个分支能编译出正常使用的固件，才学着做一个新的分支用来同步新的源码吃螃蟹用。期待修复，感谢。

**Comment by bonnyandsky** [comment]
对了，我去尝试下分支里编译固件的yml有没有问题。如果有，我再来反馈

**Comment by KFERMercer** [comment]
已修复
