### ISSUE TITLE
关于编译后固件名称的建议

### ISSUE THREAD

**Issue by engineerlzk** [KFERMercer/OpenWrt-CI#19]
感谢大大的自动编译脚本！

可不可以将编译的固件文件名添加脚本实现文件名称中包含【固件平台】、编译日期（且根据前面的设置和编译日期自动添加），比如Openwrt-X64-2019-12-10式样？

谢谢指教！

**Comment by KFERMercer** [comment]
仔细想一下就知道这个功能没有意义
