### ISSUE TITLE
如何暂时关闭actions 

### ISSUE THREAD

**Issue by bonnyandsky** [KFERMercer/OpenWrt-CI#23]
每次修改文件保存后都会自动触发acitons进行编译。请问如何关闭这个功能。需要的时候再打开？

**Comment by barton0426** [comment]
on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 10 * * *
把on后面的东西注释掉 #

**Comment by KFERMercer** [comment]
Settings - Actions - Disable Actions for this repository
