### ISSUE TITLE
请问如何添加网卡驱动呢？

### ISSUE THREAD

**Issue by Mitchell08** [KFERMercer/OpenWrt-CI#24]
我的网卡是 AR8151 Gigabit Ethernet Controller ，应该如何添加驱动呢？

**Comment by KFERMercer** [comment]
去op官方论坛找了一下:
https://forum.openwrt.org/t/x86-build-custom-lan-card-driver-install/37785/6
貌似AR8151对应的内核模块名是`kmod-atl1c`
这样的话只需要添加这一行就行了:
```
CONFIG_PACKAGE_kmod-atl1c=y
```
你可以试试看.
