### ISSUE TITLE
安装变量失败麻烦看看。

### ISSUE THREAD

**Issue by lbbboy** [KFERMercer/OpenWrt-CI#25]
[OpenWrt-CI](https://github.com/lbbboy/OpenWrt-CI/commit/105f63b3aecc1167715b343b0f5dcda5cea26cb0/checks?check_suite_id=356346628)

Process completed with exit code 100.

**Comment by RGGGong** [comment]
我用最新的也出现了同样的错误

**Comment by lbbboy** [comment]
> 我用最新的也出现了同样的错误

要好先fork openwrt 或者 lean的项目然后上传文件。单独运行文件不行。
