### ISSUE TITLE
请问关于定时同步运行的问题

### ISSUE THREAD

**Issue by bonnyandsky** [KFERMercer/OpenWrt-CI#26]
请教kfer大大，这几天发现merge-upstream.yml不会定时运行。
然后我今天早上8点半的时候吧里面的时间改成了utc 0点45运行。结果我刚才看了下还是没有运行。请问是哪里的问题。
我只是修改了分支的名字而已，其他没修改
![1](https://user-images.githubusercontent.com/30990861/70764915-fc638500-1d93-11ea-8be0-b3c71fe42a1c.png)
actions里面显示2天前才执行过中间并没有自动运行过
![2](https://user-images.githubusercontent.com/30990861/70764923-02f1fc80-1d94-11ea-9751-72937831e13d.png)
设置里也是打开相关选项的
![3](https://user-images.githubusercontent.com/30990861/70764924-038a9300-1d94-11ea-8b97-09fc8c02acf3.png)

**Comment by orzsun** [comment]
我的是不定时编译，已经把定时开了

**Comment by KFERMercer** [comment]
由于没看到你的原文件, 我感觉是因为你改成零点45的时候已经过了当天的指定时间了, 所以定时任务会等到后一天才运行.

**Comment by bonnyandsky** [comment]
这个0点45是utc时间吧，时间北京时间是8点45？我修改的时候才8点40不到
