### ISSUE TITLE
最新配置文件已GG

### ISSUE THREAD

**Issue by adaaaaaa** [KFERMercer/OpenWrt-CI#28]
/home/runner/work/_temp/a1473c58-c897-4eec-b8e9-fcd73e460d64.sh: line 4: /etc/apt/sources.list: Permission denied
##[error]Process completed with exit code 1.

**Comment by KFERMercer** [comment]
回滚了. 我得去读一下GitHub action的文档.

**Comment by adaaaaaa** [comment]
> 回滚了. 我得去读一下GitHub action的文档.

好像只需要你原来删除连续两行的第二行后面加上"/*"就可以了。。。
就添加这两个字符。。。不需要改动那么多。。。🙃🙃🙃

**Comment by KFERMercer** [comment]
?
