### ISSUE TITLE
去掉多个默认配置的插件去掉后编译失败

### ISSUE THREAD

**Issue by siryle1213** [KFERMercer/OpenWrt-CI#3]
比如去掉ipsec-vpnd插件
       # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
请问语法正确吗？有需要注意的吗

编译失败信息显示：
Annotations: 1 failure
 .github:1

Process completed with exit code 2.

**Comment by KFERMercer** [comment]
检查一下缩进是否对齐

**Comment by garypang13** [comment]
我也是,,一加上这个代码就编译错误,缩进确定没有错.
