### ISSUE TITLE
计划任务触发Merge-upstream,且有从上游了marge了内容的情况下,未能自动触发Openwrt-CI

### ISSUE THREAD

**Issue by kiddin9** [KFERMercer/OpenWrt-CI#33]
测试了很多次都不行,Merge-upstream未做任何改动,Openwrt-CI有添加
```
  push:
    branches:
      - master
```
如果是自己commit内容每次都能触发.
还是说没有如果marge了内容就自动触发Openwrt-CI这个机制,要自动编译的话openwrt-ci也要设定计划任务呢,
谢谢.

**Comment by KFERMercer** [comment]
bot 发起的推送不会触发.
