### ISSUE TITLE
编译x86，添加以下php环境插件，编译后发现固件里并没有php环境的以下插件 ，这个要怎么解决呢？

### ISSUE THREAD

**Issue by xinpenghan** [KFERMercer/OpenWrt-CI#34]
编译x86，添加以下php环境插件，编译后发现固件里并没有php环境的以下插件  ，这个要怎么解决呢？       
          CONFIG_PACKAGE_php7-fpm=y
          CONFIG_PACKAGE_php7-mod-curl=y
          CONFIG_PACKAGE_php7-mod-gd=y
          CONFIG_PACKAGE_php7-mod-iconv=y
          CONFIG_PACKAGE_php7-mod-json=y
          CONFIG_PACKAGE_php7-mod-mbstring=y
          CONFIG_PACKAGE_php7-mod-opcache=y
          CONFIG_PACKAGE_php7-mod-session=y
          CONFIG_PACKAGE_php7-mod-zip=y

**Comment by KFERMercer** [comment]
`CONFIG_PACKAGE_php7=y`
