### ISSUE TITLE
merge无法正确触发ci

### ISSUE THREAD

**Issue by barton0426** [KFERMercer/OpenWrt-CI#35]
fork的lean的库，在lean有更新，commit部分领先部分落后的情况下，观察了几天了，merge定时运行后，无法触发ci自动编译

**Comment by miaoxinwei** [comment]
on:
  pull_request:
    types: [synchronize]
    branches:
      - master

如果你想在merge lean代码是才触发打包的话 将ci的on改成这个

**Comment by KFERMercer** [comment]
github bot 的提交不会触发工作流程.
