### ISSUE TITLE
編譯其他架構固件顯示能完成，但是下載文件爲0字節

### ISSUE THREAD

**Issue by jiangxi14520** [KFERMercer/OpenWrt-CI#38]
感謝大佬的自動編譯程序，我也能夠按照大佬的方法自行定製一些X86的固件，並且能夠正常的編譯下載，但是當我想編譯樹莓派的固件的時候，顯示編譯成功，但是當我下載的時候卻發現文件爲0字節，請問是什麼原因呢？附上我的raspi和X86文本及圖片，
[openwrt-ci.txt](https://github.com/KFERMercer/OpenWrt-CI/files/4024897/openwrt-ci.txt)
[openwrt-ci-raspi.txt](https://github.com/KFERMercer/OpenWrt-CI/files/4024895/openwrt-ci-raspi.txt)
![1578290860(1)](https://user-images.githubusercontent.com/17452630/71798673-fb213180-308d-11ea-919c-43297f2c3cb7.jpg)
從圖片上來看感覺並沒有編譯生成任何文件，我x86和樹莓派都是將.config裏的所有未註釋的條目全部複製進去，但是X86能編譯成功，樹莓派顯示成功，但是沒有任何文件產生。

**Comment by KFERMercer** [comment]
CI脚本的老版本固件文件匹配的问题, 更新到最新版本即可.
