### ISSUE TITLE
编译成功了，请教几个问题，谢谢🙏

### ISSUE THREAD

**Issue by hououinkami** [KFERMercer/OpenWrt-CI#44]
1.我没有添加KMS服务器和网络唤醒两个app，但您编译成功后安装完发现带了这两个app，这是什么原因呢？能否不让固件编译进去这两个app呢？
2.能否可以自定义使得编译后的固件压缩包里只包含uefi版的那个包呢？
谢谢🙏

**Comment by Juijote** [comment]
这个应该是默认自带的,要配置里移除.

**Comment by hououinkami** [comment]
> 这个应该是默认自带的,要配置里移除.

是加一条对应的app然后后面“=n”吗？

**Comment by Juijote** [comment]
# CONFIG_PACKAGE_luci-app-pagekitec is not set
例如这样,包括需要添加#号
