### ISSUE TITLE
使用你的脚本编译了64位lene的openwrt没有问题，多谢作者，修改了你的脚本编译32位报错，请指教一下？

### ISSUE THREAD

**Issue by zhang007z** [KFERMercer/OpenWrt-CI#47]
编译64位
          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          EOF
修改了为：
          # 编译32位固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_generic=y
          CONFIG_TARGET_x86_generic_Generic=y
          EOF
然后32版本编译出错了，请问修改为32版本，是不是这样就可以了呢？多谢

**Comment by KFERMercer** [comment]
去用https://github.com/P3TERX/Actions-OpenWrt, 他的只需要上传.config文件就可以, 不需要考虑语法问题.
