### ISSUE TITLE
如何在线编译出来文件带config.seed文件在压缩包里呢

### ISSUE THREAD

**Issue by segadrive** [KFERMercer/OpenWrt-CI#48]
编译出来只有一个固件，想同时带有config.seed文件方便查看

**Comment by KFERMercer** [comment]
现在就会有啊

**Comment by segadrive** [comment]
> 现在就会有啊

我用你的代码在线编译lean的固件出来只有一个文件

**Comment by KFERMercer** [comment]
为什么不试试解压呢

**Comment by KFERMercer** [comment]
我明白了, 你是想单独可以下载到config.seed, 有时间我会加上.

**Comment by segadrive** [comment]
> 我明白了, 你是想单独可以下载到config.seed, 有时间我会加上.

嗯嗯，谢谢大佬
