### ISSUE TITLE
这个报错会出什么问题吗？？

### ISSUE THREAD

**Issue by adaaaaaa** [KFERMercer/OpenWrt-CI#5]
/home/runner/work/lede/lede/.config:36: *** missing separator.  Stop.

/home/runner/work/lede/lede/.config:36: *** missing separator.  Stop.
\#
\# configuration written to .config
\#
-----------------------------------------------------------------------------------

这个报错会出什么问题吗？？
对应的36-40行是这样的：

-----------------------------------------------------------------------------------
  \# 
  
  \# 编译x64固件:
  cat >> .config <<EOF
  CONFIG_TARGET_x86=y
-----------------------------------------------------------------------------------

好像没看到哪里有问题啊？？

**Comment by KFERMercer** [comment]
因为排版混乱, 所以看不懂
