### ISSUE TITLE
github update can't push as a bot.

### ISSUE THREAD

**Issue by cloudiesky** [KFERMercer/OpenWrt-CI#50]
Cannot push as a bot.

 Push Commits3s
##[error]Process completed with exit code 1.
Run git push --force origin $DOWNSTREAM_BRANCH
To https://github.com/cloudiesky/lede
 ! [remote rejected]   master -> master (refusing to allow a bot to create or update workflow `.github/workflows/openwrt-ci.yml`)
error: failed to push some refs to 'https://github.com/cloudiesky/lede'
##[error]Process completed with exit code 1.

**Comment by KFERMercer** [comment]
github actions doesn't allow it to change workflow files by self
