### ISSUE TITLE
关于自动同步lede脚本的问题

### ISSUE THREAD

**Issue by bonnyandsky** [KFERMercer/OpenWrt-CI#52]
你好，今天才发现你写的自动同步lede的脚本貌似不能正常工作了。2月22日开始编译失败的，之前都能正常编译，具体请看下截图，请问如何修改才可以正常同步lede的脚本？
![1](https://user-images.githubusercontent.com/30990861/76928683-3c9b4c00-691d-11ea-9ea1-14887e136576.png)
![2](https://user-images.githubusercontent.com/30990861/76928686-3e650f80-691d-11ea-94c3-b8937bbcdcbe.png)

**Comment by wentijianihao** [comment]
重新fork大雕的源码。
