### ISSUE TITLE
改动了下固件出现第一行和12行语法错误

### ISSUE THREAD

**Issue by LiuDa1982** [KFERMercer/OpenWrt-CI#53]
![QQ截图20200323230728](https://user-images.githubusercontent.com/60084929/77331493-c4d58300-6d5b-11ea-8073-04fc11d73d78.png)
![QQ截图20200323230739](https://user-images.githubusercontent.com/60084929/77331495-c69f4680-6d5b-11ea-835a-eb52f9f69bad.png)

**Comment by KFERMercer** [comment]
改了哪里?
