### ISSUE TITLE
du: cannot access '/mnt/openwrt/': No such file or directory

### ISSUE THREAD

**Issue by aceslup** [KFERMercer/OpenWrt-CI#61]
![image](https://user-images.githubusercontent.com/4714530/82619623-0756f700-9c09-11ea-9dca-25a7a4465b3d.png)

初打算编译个hc5661设备上上手，但这个报错很无厘头。在space cleanup阶段代码，我明确看到该目录是被创建了的。目前未发现在哪个阶段把 /mnt/openwrt/给删了。作者是否能抽空给予指点。感谢你的分享。

**Comment by KFERMercer** [comment]
其实没必要挂载额外空间, 本来的空间就够用了

**Comment by w37fhy** [comment]
我刚也遇到同样问题！如何解决？

**Comment by loveguag** [comment]
+1，我也遇到这个问题了，actions 跑不过。。。

**Comment by aceslup** [comment]
> , 本来的空间就够用了
感谢回复。好像一般使用者都不会去选挂还是不挂这个目录。这个选择是在yml文件操作么？

**Comment by KFERMercer** [comment]
> 感谢回复。好像一般使用者都不会去选挂还是不挂这个目录。这个选择是在yml文件操作么？

一般来说不用, 只是以备不时之需

关于 actions 编译失败, 原因是前几天官方的更新出现了 bug, 现官方已修复.

**Comment by newsharpstar** [comment]
2021-07-08T14:17:02.0975772Z du: cannot access '/mnt/openwrt/': No such file or directory
我今天编译的也是这个状况。限制在跑第二遍。
