### ISSUE TITLE
请问如何解决这个报错？

### ISSUE THREAD

**Issue by w37fhy** [KFERMercer/OpenWrt-CI#62]
![image](https://user-images.githubusercontent.com/64185417/82748114-0624f600-9dd2-11ea-974f-15a0c64aae58.png)

**Comment by KFERMercer** [comment]
现在暂时不要挂载额外空间

**Comment by w37fhy** [comment]
> 现在暂时不要挂载额外空间
请问如何取消挂载额外空间？
我是完全复制了你的yml配置，点star 开始编译的。。自己没有做其他修改。。。
需要在配置里如何修改？望指教~

**Comment by KFERMercer** [comment]
![image](https://user-images.githubusercontent.com/37098748/82776585-02e74400-9e7e-11ea-89a8-c6c1bf9633ab.png)

**Comment by w37fhy** [comment]
这几行，我直接复制你的，前面本来就是带#号 注释掉了啊。。。迷糊。

**Comment by KFERMercer** [comment]
https://github.com/fhysdwh/lede/blob/master/.github/workflows/fhy_x86.yml

很明显没注释
